apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mlops
  replicas: 1
  template:
    metadata:
      labels:
          app.kubernetes.io/name: mlops
    spec:
      containers:
      - image: asia.gcr.io/test-servers-349208/mlops:latest
        imagePullPolicy: Always
        name: mlops
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: mlops
